spring:
  application:
    name:Restro Application

  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
    url: jdbc:postgresql://localhost:5433/khana-khazana
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    dialect: org.hibernate.dialect.PostgreSQLDialect
